version: 3.7
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: asd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5439:5439'
